### ISSUE TITLE
Does not compile on gcc 5.2 (ubuntu 15.10)

### ISSUE THREAD

**Issue by goldhoorn** [rock-planning/planning-fd_cedalion#3]
First error (much more are there but yanked):

```
In file included from /usr/local/include/boost/dynamic_bitset/dynamic_bitset.hpp:42:0,
                 from /usr/local/include/boost/dynamic_bitset.hpp:15,
                 from /home/goldhoorn/dev-diss/planning/fd_cedalion/src/search/cegar/utils.h:10,
                 from /home/goldhoorn/dev-diss/planning/fd_cedalion/src/search/cegar/split_tree.h:4,
                 from /home/goldhoorn/dev-diss/planning/fd_cedalion/src/search/cegar/abstract_state.h:4,
                 from /home/goldhoorn/dev-diss/planning/fd_cedalion/src/search/cegar/abstract_state.cc:1:
/usr/local/include/boost/detail/dynamic_bitset.hpp:163:9: error: expected initializer before ‘BOOST_NOEXCEPT’
         BOOST_NOEXCEPT
         ^
In file included from /usr/local/include/boost/move/utility.hpp:28:0,
                 from /usr/local/include/boost/move/move.hpp:29,
                 from /usr/local/include/boost/dynamic_bitset/dynamic_bitset.hpp:44,
                 from /usr/local/include/boost/dynamic_bitset.hpp:15,
                 from /home/goldhoorn/dev-diss/planning/fd_cedalion/src/search/cegar/utils.h:10,
                 from /home/goldhoorn/dev-diss/planning/fd_cedalion/src/search/cegar/split_tree.h:4,
                 from /home/goldhoorn/dev-diss/planning/fd_cedalion/src/search/cegar/abstract_state.h:4,
                 from /home/goldhoorn/dev-diss/planning/fd_cedalion/src/search/cegar/abstract_state.cc:1:
/usr/local/include/boost/move/utility_core.hpp:211:89: error: expected initializer before ‘BOOST_NOEXCEPT’
          inline typename ::boost::move_detail::remove_reference<T>::type && move(T&& t) BOOST_NOEXCEPT
                                                                                         ^
/usr/local/include/boost/move/utility_core.hpp:247:90: error: expected initializer before ‘BOOST_NOEXCEPT’
          inline T&& forward(typename ::boost::move_detail::remove_reference<T>::type& t) BOOST_NOEXCEPT
                                                                                          ^
/usr/local/include/boost/move/utility_core.hpp:251:91: error: expected initializer before ‘BOOST_NOEXCEPT’
          inline T&& forward(typename ::boost::move_detail::remove_reference<T>::type&& t) BOOST_NOEXCEPT
                                                                                           ^
/usr/local/include/boost/move/utility_core.hpp:282:111: error: expected initializer before ‘BOOST_NOEXCEPT’
          inline T&& move_if_not_lvalue_reference(typename ::boost::move_detail::remove_reference<T>::type& t) BOOST_NOEXCEPT
                                                                                                               ^
/usr/local/include/boost/move/utility_core.hpp:286:112: error: expected initializer before ‘BOOST_NOEXCEPT’
          inline T&& move_if_not_lvalue_reference(typename ::boost::move_detail::remove_reference<T>::type&& t) BOOST_NOEXCEPT
                                                                                                                ^
In file included from /usr/local/include/boost/dynamic_bitset/dynamic_bitset.hpp:42:0,
                 from /usr/local/include/boost/dynamic_bitset.hpp:15,
                 from /home/goldhoorn/dev-diss/planning/fd_cedalion/src/search/cegar/utils.h:10,
                 from /home/goldhoorn/dev-diss/planning/fd_cedalion/src/search/cegar/split_tree.h:4,
                 from /home/goldhoorn/dev-diss/planning/fd_cedalion/src/search/cegar/abstraction.h:4,
                 from /home/goldhoorn/dev-diss/planning/fd_cedalion/src/search/cegar/abstraction.cc:1:
/usr/local/include/boost/detail/dynamic_bitset.hpp:163:9: error: expected initializer before ‘BOOST_NOEXCEPT’
         BOOST_NOEXCEPT

```

occusing with newest boost version but also with normal system boost version
